version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "aiturralde"
    assignees:
      - "aiturralde"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5

  # PowerShell Gallery dependencies (if any modules are added in the future)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "aiturralde"
    assignees:
      - "aiturralde"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "powershell"
    open-pull-requests-limit: 3
