name: 📚 Documentation Issue
description: Report an issue with documentation or request documentation improvements
title: "[DOCS] "
labels: ["documentation", "needs-triage"]
assignees:
  - aiturralde

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please provide details about the documentation issue or improvement.

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - "Missing documentation"
        - "Incorrect/outdated information"
        - "Unclear instructions"
        - "Typo/grammar error"
        - "New documentation needed"
        - "Formatting/structure issue"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Which file or section needs attention?
      placeholder: e.g., README.md, Config/applications.json comments, etc.
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say (if applicable)?
      placeholder: Copy/paste the current text or describe what's currently documented

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong or missing with the current documentation?
      placeholder: Describe the problem with the current documentation
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: Provide your suggested changes or additions
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who would benefit from this documentation improvement?
      options:
        - "New users"
        - "Advanced users"
        - "Developers/contributors"
        - "All users"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context that might be helpful
      placeholder: Screenshots, links, or other relevant information

  - type: checkboxes
    id: contribution
    attributes:
      label: Contributing
      description: Would you be willing to help improve the documentation?
      options:
        - label: I would be willing to submit a pull request to fix this documentation issue
